# Plugin environment configuration.
---
repositories:
 exposed: "https://dl.bintray.com/kotlin/exposed"
 gatehill: "https://gatehillsoftware-maven.s3.amazonaws.com/snapshots/"

# TODO derive these from the engine and api modules' transitive dependencies
exclusions:
 - groupId: "org.jetbrains.kotlin"
   artifactId: "kotlin-stdlib"
 - groupId: "org.jetbrains.kotlin"
   artifactId: "kotlin-reflect"
 - groupId: "org.jetbrains"
   artifactId: "annotations"
 - groupId: "javax.inject"
   artifactId: "javax.inject"
 - groupId: "org.apache.logging.log4j"
   artifactId: "log4j-api"
 - groupId: "com.google.inject"
   artifactId: "guice"
 - groupId: "com.google.guava"
   artifactId: "guava"
 - groupId: "com.fasterxml.jackson.module"
   artifactId: "jackson-module-kotlin"
 - groupId: "com.fasterxml.jackson.core"
   artifactId: "jackson-databind"
 - groupId: "com.fasterxml.jackson.core"
   artifactId: "jackson-annotations"
 - groupId: "com.fasterxml.jackson.dataformat"
   artifactId: "jackson-dataformat-yaml"
 - groupId: "com.fasterxml.jackson.core"
   artifactId: "jackson-core"
 - groupId: "org.yaml"
   artifactId: "snakeyaml"
 - groupId: "aopalliance"
   artifactId: "aopalliance"
 - groupId: "ch.qos.logback"
   artifactId: "logback-classic"
 - groupId: "org.slf4j"
   artifactId: "slf4j-api"
 - groupId: "com.gatehill.corebot"
   artifactId: "core-api"
 - groupId: "com.gatehill.corebot"
   artifactId: "core-engine"
